apiVersion: v1
kind: ConfigMap
metadata:
  name: mih-config
  namespace: mih-server
data:
  DEBUG: "false"
  DEV_MODE: "false"
  ALLOWED_HOSTS: "server-mih.ak8s.ic.unicamp.br,localhost"
  CORS_ALLOWED_ORIGINS: "https://server-mih.ak8s.ic.unicamp.br"
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  MINIO_IMAGES_BUCKET: "mih"
  MINIO_DOCUMENTS_BUCKET: "documents"
  MINIO_DOMAIN: "minio-api.ak8s.ic.unicamp.br"
  MINIO_SECURE: "true"
