apiVersion: v1
kind: Secret
metadata:
  name: mih-secret
  namespace: mih-server
type: Opaque
stringData:
  SECRET_KEY: "your-django-secret-key"
  DB_PASSWORD: "postgres"
  SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: "your-google-oauth-client-id"
  SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: "your-google-oauth-client-secret"
  MINIO_ACCESS_KEY: "your-minio-access-key"
  MINIO_SECRET_KEY: "your-minio-secret-key"
