
"""teste

Revision ID: 1dd0a3e9c678
Revises: e0d403257d8f
Create Date: 2024-11-29 11:40:26.598368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dd0a3e9c678'
down_revision: Union[str, None] = 'e0d403257d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('images_created_by_fkey', 'images', type_='foreignkey')
    op.create_foreign_key(None, 'images', 'user', ['user_id'], ['id'])
    op.drop_column('images', 'created_by')
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('RESPONSIBLE', 'SPECIALIST', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('RESPONSIBLE', 'SPECIALIST', name='userrole'),
               nullable=False)
    op.add_column('images', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_foreign_key('images_created_by_fkey', 'images', 'user', ['created_by'], ['id'])
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###
