"""Autenticacao

Revision ID: 23106d987ec3
Revises: 
Create Date: 2024-11-22 02:00:14.417092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '23106d987ec3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mih', sa.Column('painLevel', sa.Integer(), nullable=True))
    op.add_column('mih', sa.Column('sensitivityField', sa.Boolean(), nullable=True))
    op.add_column('patients', sa.Column('deliveryProblemsTypes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('personInCharge', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user', 'motherName')
    op.drop_column('user', 'fatherName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fatherName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('motherName', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'personInCharge')
    op.drop_column('patients', 'deliveryProblemsTypes')
    op.drop_column('mih', 'sensitivityField')
    op.drop_column('mih', 'painLevel')
    # ### end Alembic commands ###
