
"""mih

Revision ID: 51637340d0d6
Revises: 1dd0a3e9c678
Create Date: 2024-11-29 12:26:06.317415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51637340d0d6'
down_revision: Union[str, None] = '1dd0a3e9c678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mih', sa.Column('photo_id1', sa.Integer(), nullable=False))
    op.add_column('mih', sa.Column('photo_id2', sa.Integer(), nullable=False))
    op.add_column('mih', sa.Column('photo_id3', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mih', 'photo_id3')
    op.drop_column('mih', 'photo_id2')
    op.drop_column('mih', 'photo_id1')
    # ### end Alembic commands ###
