"""Novas definições patients

Revision ID: 9cdcf896d0eb
Revises: 6b56377088e6
Create Date: 2024-10-04 16:56:21.159524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9cdcf896d0eb'
down_revision: Union[str, None] = '6b56377088e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('consultType', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('patients', 'consultDentist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('consultDentist', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('patients', 'consultType')
    # ### end Alembic commands ###
