"""Relaçoes user 4

Revision ID: bc62bacff85d
Revises: f27b72673300
Create Date: 2024-10-14 09:55:36.977250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bc62bacff85d'
down_revision: Union[str, None] = 'f27b72673300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mih', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mih', 'patients', ['patient_id'], ['patient_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mih', type_='foreignkey')
    op.drop_column('mih', 'patient_id')
    # ### end Alembic commands ###
