"""Novas colunas

Revision ID: c899bb96077d
Revises: 
Create Date: 2024-10-03 00:43:40.254241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c899bb96077d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mih', sa.Column('painLevel', sa.Integer(), nullable=True))
    op.add_column('mih', sa.Column('sensitivityField', sa.Boolean(), nullable=True))
    op.add_column('mih', sa.Column('stain', sa.Boolean(), nullable=True))
    op.add_column('mih', sa.Column('aestheticDiscomfort', sa.Boolean(), nullable=True))
    op.add_column('mih', sa.Column('userObservations', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mih', sa.Column('specialistObservations', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mih', sa.Column('diagnosis', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('mih', 'mih_location')
    op.drop_column('patients', 'observations')
    op.add_column('user', sa.Column('motherName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('fatherName', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('neighborhood', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'accept_tcle',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('user', 'accept_tcle',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('user', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'neighborhood')
    op.drop_column('user', 'state')
    op.drop_column('user', 'city')
    op.drop_column('user', 'fatherName')
    op.drop_column('user', 'motherName')
    op.add_column('patients', sa.Column('observations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('mih', sa.Column('mih_location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('mih', 'diagnosis')
    op.drop_column('mih', 'specialistObservations')
    op.drop_column('mih', 'userObservations')
    op.drop_column('mih', 'aestheticDiscomfort')
    op.drop_column('mih', 'stain')
    op.drop_column('mih', 'sensitivityField')
    op.drop_column('mih', 'painLevel')
    # ### end Alembic commands ###
