"""Relaçoes user 3

Revision ID: f27b72673300
Revises: 7db08b650274
Create Date: 2024-10-14 09:32:17.502685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f27b72673300'
down_revision: Union[str, None] = '7db08b650274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mih_user_id_fkey', 'mih', type_='foreignkey')
    op.drop_constraint('mih_patient_id_fkey', 'mih', type_='foreignkey')
    op.drop_column('mih', 'user_id')
    op.drop_column('mih', 'patient_id')
    op.drop_constraint('trackingrecords_patient_id_fkey', 'trackingrecords', type_='foreignkey')
    op.drop_constraint('trackingrecords_specialist_id_fkey', 'trackingrecords', type_='foreignkey')
    op.drop_constraint('trackingrecords_mih_id_fkey', 'trackingrecords', type_='foreignkey')
    op.drop_column('trackingrecords', 'specialist_id')
    op.drop_column('trackingrecords', 'patient_id')
    op.drop_column('trackingrecords', 'mih_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackingrecords', sa.Column('mih_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trackingrecords', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trackingrecords', sa.Column('specialist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('trackingrecords_mih_id_fkey', 'trackingrecords', 'mih', ['mih_id'], ['mih_id'])
    op.create_foreign_key('trackingrecords_specialist_id_fkey', 'trackingrecords', 'specialists', ['specialist_id'], ['specialist_id'])
    op.create_foreign_key('trackingrecords_patient_id_fkey', 'trackingrecords', 'patients', ['patient_id'], ['patient_id'])
    op.add_column('mih', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('mih', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('mih_patient_id_fkey', 'mih', 'patients', ['patient_id'], ['patient_id'])
    op.create_foreign_key('mih_user_id_fkey', 'mih', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
