# Generated by Django 5.2.11 on 2026-02-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_concept_id_1', models.IntegerField(blank=True, null=True)),
                ('domain_concept_id_2', models.IntegerField(blank=True, null=True)),
                ('fact_id_1', models.IntegerField(blank=True, null=True)),
                ('fact_id_2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('address_1', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('highFever', models.BooleanField(null=True)),
                ('premature', models.BooleanField(null=True)),
                ('deliveryProblems', models.BooleanField(null=True)),
                ('lowWeight', models.BooleanField(null=True)),
                ('deliveryType', models.CharField(blank=True, max_length=255, null=True)),
                ('brothersNumber', models.IntegerField(blank=True, null=True)),
                ('consultType', models.CharField(blank=True, max_length=255, null=True)),
                ('deliveryProblemsTypes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True)),
                ('photo_id1', models.IntegerField(blank=True, null=True)),
                ('photo_id2', models.IntegerField(blank=True, null=True)),
                ('photo_id3', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('painLevel', models.IntegerField(blank=True, null=True)),
                ('sensitivityField', models.BooleanField(null=True)),
                ('stain', models.BooleanField(null=True)),
                ('aestheticDiscomfort', models.BooleanField(null=True)),
                ('userObservations', models.TextField(blank=True, null=True)),
                ('specialistObservations', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mih', to='mih.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_source_value', models.CharField(blank=True, max_length=512, null=True)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('month_of_birth', models.IntegerField(blank=True, null=True)),
                ('day_of_birth', models.IntegerField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mih.location')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_concept_id', models.IntegerField(blank=True, null=True)),
                ('value_as_number', models.FloatField(blank=True, null=True)),
                ('measurement_date', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mih.person')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_source_value', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mih.location')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_concept_id', models.IntegerField(blank=True, null=True)),
                ('value_as_number', models.FloatField(blank=True, null=True)),
                ('value_as_concept_id', models.IntegerField(blank=True, null=True)),
                ('value_as_string', models.TextField(blank=True, null=True)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mih.person')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mih.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ConditionOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_concept_id', models.IntegerField(blank=True, null=True)),
                ('condition_start_date', models.DateTimeField(blank=True, null=True)),
                ('condition_end_date', models.DateTimeField(blank=True, null=True)),
                ('condition_type_concept_id', models.IntegerField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mih.person')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mih.provider')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mih', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='mih.mih')),
            ],
        ),
        migrations.CreateModel(
            name='VisitOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_concept_id', models.IntegerField(blank=True, null=True)),
                ('visit_start_date', models.DateTimeField(blank=True, null=True)),
                ('visit_end_date', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mih.person')),
            ],
        ),
    ]
