# Generated by Django 5.2.11 on 2026-02-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mih', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file',
            field=models.FileField(default=1, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
