# Generated by Django 5.2.11 on 2026-02-20 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mih', '0002_image_file_alter_image_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('responsible', 'Responsible'), ('specialist', 'Specialist')], max_length=32, null=True)),
                ('is_allowed', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('state', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=128, null=True)),
                ('accept_tcle', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
