# Generated by Django 5.2.11 on 2026-02-20 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mih', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingrecord',
            name='mih',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mih',
        ),
        migrations.DeleteModel(
            name='TrackingRecord',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
