# Generated by Django 5.2.11 on 2026-03-01 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mih', '0005_person_birth_datetime_person_gender_concept_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientnonclinicalinfos',
            name='accept_tcl',
        ),
        migrations.RemoveField(
            model_name='patientnonclinicalinfos',
            name='bind_code',
        ),
        migrations.RemoveField(
            model_name='patientnonclinicalinfos',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_care_site_registration',
        ),
        migrations.RemoveField(
            model_name='person',
            name='person_user_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='provider_birthday',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialty_string',
        ),
    ]
