# Generated by Django 6.0.2 on 2026-04-09 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mih', '0007_image_minio_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providernonclinicalinfos',
            name='accept_tcle',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='accept_tcle',
        ),
        migrations.CreateModel(
            name='ConsentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('tcle', 'TCLE (Termo de Consentimento Livre e Esclarecido)'), ('privacy_policy', 'Privacy Policy')], db_index=True, max_length=32)),
                ('version', models.CharField(db_index=True, max_length=32)),
                ('language', models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en', 'English')], default='pt-BR', max_length=10)),
                ('file_path', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=64)),
                ('file_size', models.BigIntegerField()),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('effective_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('changelog', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consent_type', 'language', '-effective_date'], name='mih_consent_consent_c85ade_idx'), models.Index(fields=['content_hash'], name='mih_consent_content_d06dcb_idx'), models.Index(fields=['is_active', 'consent_type'], name='mih_consent_is_acti_c50115_idx')],
                'unique_together': {('consent_type', 'version', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('tcle', 'TCLE (Termo de Consentimento Livre e Esclarecido)'), ('privacy_policy', 'Privacy Policy')], max_length=32)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='mih.consentdocument')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consent_type', '-created_at'], name='mih_consent_user_id_ace2e5_idx'), models.Index(fields=['document', 'accepted'], name='mih_consent_documen_c3d26d_idx'), models.Index(fields=['created_at'], name='mih_consent_created_b8b313_idx')],
            },
        ),
    ]
