# Generated by Django 6.0.2 on 2026-04-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mih', '0008_remove_providernonclinicalinfos_accept_tcle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentdocument',
            name='requires_reconsent',
            field=models.BooleanField(default=False),
        ),
    ]
