# Generated by Django 6.0.2 on 2026-04-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mih', '0009_consentdocument_requires_reconsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providernonclinicalinfos',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
