# Generated by Django 6.0.2 on 2026-04-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mih', '0010_alter_providernonclinicalinfos_is_allowed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tale_consents', to='mih.person'),
        ),
        migrations.AlterField(
            model_name='consent',
            name='consent_type',
            field=models.CharField(choices=[('tcle', 'TCLE (Termo de Consentimento Livre e Esclarecido)'), ('privacy_policy', 'Privacy Policy'), ('tale_6_9', 'TALE (6–9 anos)'), ('tale_10_12', 'TALE (10–12 anos)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='consentdocument',
            name='consent_type',
            field=models.CharField(choices=[('tcle', 'TCLE (Termo de Consentimento Livre e Esclarecido)'), ('privacy_policy', 'Privacy Policy'), ('tale_6_9', 'TALE (6–9 anos)'), ('tale_10_12', 'TALE (10–12 anos)')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['patient', 'consent_type', '-created_at'], name='mih_consent_patient_fc340b_idx'),
        ),
    ]
